//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public string Mota { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Price { get; set; }
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
